### ISSUE TITLE
ayuda, no funciona login el Hosting 

### ISSUE THREAD

**Issue by famjaes** [Developero-oficial/php-mvc#2]
Excelente aporte, en local funciona perfectamente, pero cuando lo subo a un hosting en linea sucede lo siguiente 
Cuando  tecleo en la barra de direcciones lo siguiente  
http://misitio.x10.mx/hola/Login/           La pagina se queda en blanco,   (mal funcionamiento) 

http://misitio.x10.mx/hola/xydsf          Se muestra la pagina de error 404   (Correcto)
http://misitio.x10.mx/hola/                 Se muestra hola mundo (Correcto) 
http://misitio.x10.mx/Home/      Se muestra hola mundo (Correcto) 

Cualquier ayuda te lo agradeceré de antemano saludos

**Comment by juan-carlos-correa** [comment]
Hola,

Te respondí en e[l vídeo de YouTube](https://www.youtube.com/watch?v=3l6fJ1a5bo0&lc=z22lh5aosrfeibrcpacdp435hcish4ndq5z2ybkovolw03c010c)

"Login" debe corresponder con el archivo "LoginController.php" para que te redirija.﻿

Por otra parte, este mini framework lo cree únicamente para propósitos educativos, no lo recomiendo para entornos de producción porque tiene vulnerabilidades.

Digo esto sólo por si tienes en mente usarlo en prod. Si es sólo para experimentar está perfecto, incluso los PR son bienvenidos :D

**Comment by juan-carlos-correa** [comment]
Sin actividad
