### ISSUE TITLE
Crear rama con un ejemplo de landing page

### ISSUE THREAD

**Issue by juan-carlos-correa** [Developero-oficial/php-mvc#4]
Un ejemplo de landing page en su rama pertinente.

Landing page me refiero a una página de inicio donde se hace un resumen del contenido.

La propuesta es hacer una landing page sobre este mini framework en php-mvc/app/views/Home/Home.php

Es libre el diseño, sólo hay que agregar información relacionada :)

**Comment by liloo2040** [comment]
Hola! Quiero hacerlo !

**Comment by juan-carlos-correa** [comment]
> Hola! Quiero hacerlo !

Adelante! :D
